### ISSUE TITLE
Error Initializing One Connect and can't connect to VPN Server

### ISSUE THREAD

**Issue by aannurwahidi7** [oneconnectapi/Oneconnect-flutter-demo#4]
I am a new developer, currently building a new VPN with One Connect SDK in iOS, but I have a problem when I'm trying to connect to VPN server it doesn't do anything, in log before connecting VPN server it says :

> `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-4, IPC failed, IPC failed, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous 
#2      OpenVPN.initialize.<anonymous closure> (package:oneconnect_flutter/src/vpn_engine.dart:123:13)
<asynchronous> `

Please help me, Thank you.

**Comment by oneconnectapi** [comment]
https://github.com/oneconnectapi/Oneconnect-flutter-demo/issues/2#issuecomment-2382845528 check this
