### ISSUE TITLE
Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by Dhaval01807** [oneconnectapi/Oneconnect-flutter-demo#5]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-4, IPC failed, IPC failed, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      OpenVPN.initialize.<anonymous closure> (package:oneconnect_flutter/src/vpn_engine.dart:123:13)
<asynchronous suspension>

//Function To Start Or Connect To Vpn Engine
 void initialize(BuildContext context) {
    
    engine = OpenVPN(
        onVpnStageChanged: onVpnStageChanged,
        onVpnStatusChanged: onVpnStatusChanged)
      ..initialize(
        lastStatus: onVpnStatusChanged,
        lastStage: (stage) => onVpnStageChanged(stage, stage.name),
        groupIdentifier: groupIdentifier,
        localizedDescription: localizationDescription,
        providerBundleIdentifier: providerBundleIdentifier,
      );
  }

I Have Facing Difficulty In IOS Build Or Execution 
Can You Provide With Solution Or Proper Documentation Of IOS

**Comment by oneconnectapi** [comment]
Hi, may i know the xcode version
